[package]
name = "mem_broker"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13.5"
actix-web = "4.9.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.132"
tokio = "1.41.0"


[features]
remote = []
